package life.myblog.model;

public class Visitor {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitor.ip
     *
     * @mbg.generated Wed Sep 29 15:49:52 CST 2021
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitor.place
     *
     * @mbg.generated Wed Sep 29 15:49:52 CST 2021
     */
    private String place;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitor.datetime
     *
     * @mbg.generated Wed Sep 29 15:49:52 CST 2021
     */
    private String datetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visitor.ip
     *
     * @return the value of visitor.ip
     *
     * @mbg.generated Wed Sep 29 15:49:52 CST 2021
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visitor.ip
     *
     * @param ip the value for visitor.ip
     *
     * @mbg.generated Wed Sep 29 15:49:52 CST 2021
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visitor.place
     *
     * @return the value of visitor.place
     *
     * @mbg.generated Wed Sep 29 15:49:52 CST 2021
     */
    public String getPlace() {
        return place;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visitor.place
     *
     * @param place the value for visitor.place
     *
     * @mbg.generated Wed Sep 29 15:49:52 CST 2021
     */
    public void setPlace(String place) {
        this.place = place == null ? null : place.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visitor.datetime
     *
     * @return the value of visitor.datetime
     *
     * @mbg.generated Wed Sep 29 15:49:52 CST 2021
     */
    public String getDatetime() {
        return datetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visitor.datetime
     *
     * @param datetime the value for visitor.datetime
     *
     * @mbg.generated Wed Sep 29 15:49:52 CST 2021
     */
    public void setDatetime(String datetime) {
        this.datetime = datetime == null ? null : datetime.trim();
    }
}