package life.myblog.mapper;

import java.util.List;
import life.myblog.model.Visitor;
import life.myblog.model.VisitorExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface VisitorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitor
     *
     * @mbg.generated Wed Sep 29 15:49:52 CST 2021
     */
    long countByExample(VisitorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitor
     *
     * @mbg.generated Wed Sep 29 15:49:52 CST 2021
     */
    int deleteByExample(VisitorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitor
     *
     * @mbg.generated Wed Sep 29 15:49:52 CST 2021
     */
    int deleteByPrimaryKey(String ip);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitor
     *
     * @mbg.generated Wed Sep 29 15:49:52 CST 2021
     */
    int insert(Visitor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitor
     *
     * @mbg.generated Wed Sep 29 15:49:52 CST 2021
     */
    int insertSelective(Visitor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitor
     *
     * @mbg.generated Wed Sep 29 15:49:52 CST 2021
     */
    List<Visitor> selectByExampleWithRowbounds(VisitorExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitor
     *
     * @mbg.generated Wed Sep 29 15:49:52 CST 2021
     */
    List<Visitor> selectByExample(VisitorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitor
     *
     * @mbg.generated Wed Sep 29 15:49:52 CST 2021
     */
    Visitor selectByPrimaryKey(String ip);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitor
     *
     * @mbg.generated Wed Sep 29 15:49:52 CST 2021
     */
    int updateByExampleSelective(@Param("record") Visitor record, @Param("example") VisitorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitor
     *
     * @mbg.generated Wed Sep 29 15:49:52 CST 2021
     */
    int updateByExample(@Param("record") Visitor record, @Param("example") VisitorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitor
     *
     * @mbg.generated Wed Sep 29 15:49:52 CST 2021
     */
    int updateByPrimaryKeySelective(Visitor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitor
     *
     * @mbg.generated Wed Sep 29 15:49:52 CST 2021
     */
    int updateByPrimaryKey(Visitor record);
}